export const employeeProfileRequiredFields = [
  "permanentAddress",
  "currentAddress",
  "emergencyContactName",
  "emergencyContactId",
  "emergencyContactAddress",
  "emergencyContactPhone",
  "emergencyContactRelationship",
  "contactNumber",
  "email",
  "linkedInId",
  "dateOfBirth",
  "maritalStatus",
  "spouseName",
  "spouseId",
] as const;
